[package]
name = "elya"
version = "0.0.1"
edition = "2021"
rust-version = "1.75"

[lib]
name = "elya"
path = "src/lib.rs"

[[bin]]
name = "elya"
path = "src/main.rs"

[dependencies]
logos = "0.14"
ariadne = "0.4"
inkwell = { version = "0.5", default-features = false, features = ["llvm18-0", "target-x86"], optional = true }

[features]
codegen = ["dep:inkwell"]

[dev-dependencies]
insta = "1"
